routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Comuns
Auth::routes();
Route::get('/', 'HomeController@index')->name('inicio');
Route::get('/home', 'HomeController@index')->name('home');

//Block de Registros externos
Route::any('/register', function () {
    return redirect()->route('inicio');
});

//Rotas Administrativas
Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('distribuicao', 'DistribuicaoCrudController');
    Route::resource('reunioes', 'ReuniaoCrudController');
    Route::resource('usuarios', 'UsuarioCrudController');
    Route::resource('entidades', 'OrgaoCrudController');
    Route::resource('pauta', 'PautaCrudController');
    Route::resource('itempauta', 'ItemPautaCrudController');
    Route::get('usuarios-removidos', 'UsuarioCrudController@removidos')->name('removidos');
    Route::post('perma-delete/{id}', 'UsuarioCrudController@forceDelete')->name('delete-user');
    Route::post('restaurar-usuario/{id}', 'UsuarioCrudController@restore')->name('restore-user');
    Route::get('arquivos', 'NovoElfinderController@showIndex')->name('arquivos');
});

//Rota que Altera o Gerenciador de Arquivos
Route::group(array('middleware'=>'auth', 'namespace' => 'Admin'),function(){
    Route::any('connector', ['as' => 'elfinder.connector', 'uses' => 'NovoElfinderController@showConnectorext']);
});

Route::group(['middleware' => 'auth'], function () {
    // Rotas do Perfil
    Route::get('perfil', 'Admin\PerfilController@perfil')->name('perfil');
    Route::put('perfil', 'Admin\PerfilController@perfilUpdate')->name('perfilUpdate');
    Route::put('resetSenha', 'Admin\PerfilController@resetSenha')->name('resetSenha');

    // Rotas da Imagem do Perfil
    Route::put('alterFoto', 'Admin\PerfilController@alterFoto')->name('alterFoto');

    // Rotas das Reuniões - Comuns
    Route::get('reunioes', 'ReuniaoController@index');
    Route::get('reunioes/participar/{reuniao}', 'ReuniaoController@participar')->name('participar');
    Route::post('reunioes/votar', 'ReuniaoController@votar');
    Route::post('reunioes/{reuniao}/abrir', 'ReuniaoController@abrir');
    Route::post('reunioes/{reuniao}/encerrar', 'ReuniaoController@encerrar');
    Route::post('reunioes/{reuniao}/checar', 'ReuniaoController@checar');

    // JSON
    Route::get('reuniao/{reuniao}/load', 'ReuniaoController@loadJSON');
    Route::get('item/{item}/votos', 'ReuniaoController@votosJSON');
    Route::get ('quorum/count/{id}',    'ReuniaoController@quorumCount');
    Route::get ('quorum/users/{id}',    'ReuniaoController@quorumUsers');

    // Rotas de Respostas AJAX
    Route::get('getPautas/{id}', 'AjaxRequestsController@getPautas')->name('getPautas');
    Route::get('getUsers/{id}', 'AjaxRequestsController@getUsers')->name('getQuorum');
    Route::get('getReunions', 'AjaxRequestsController@getReunions')->name('getReunions');
    Route::any('delPauta/{id}', 'AjaxRequestsController@delPauta')->name('delPauta');
    Route::get('addItemView/{id}', 'AjaxRequestsController@addItemView')->name('addItem');
    Route::post('liberarItem/{id}', 'AjaxRequestsController@liberarItem')->name('liberarItem');
    Route::post('encerrarItem/{id}', 'AjaxRequestsController@encerrarItem')->name('encerrarItem');
    Route::get('historicoUser/{user}', 'AjaxRequestsController@historicoUser')->name('historicoUser');
    Route::get('historicoReuniao/{reuniao}', 'AjaxRequestsController@historicoReuniao')->name('historicoReuniao');
});

resources/views/admin/reunioes/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-globe"></i> Administração de Reuniões</h5>
                        <hr>
                        <a href="{{ route('reunioes.index') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-backward"></i> Voltar
                        </a>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="application/x-www-form-urlencoded" novalidate action="{{ route('reunioes.store') }}">
                            @csrf
                            <div class="form-row align-items-center">
                                <div class="col-sm-12 col-md-12">
                                    <label class="sr-only" for="descricao">Descrição</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-font"></i></div>
                                        </div>
                                        <textarea class="form-control {{ $errors->has('descricao') ? ' is-invalid' : '' }}"
                                                  id="descricao"
                                                  name="descricao"
                                                  placeholder="Descrição da Reunião" required>{{ old('descricao') }}</textarea>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-5">
                                    <label class="sr-only" for="data">Data</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                        <input type="date" class="form-control {{ $errors->has('data') ? ' is-invalid' : '' }}" id="data" name="data" placeholder="dd/mm/aaaa">
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-5">
                                    <label class="sr-only" for="status">Status</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-info"></i></div>
                                        </div>
                                        <select id="status" readonly required name="status" class="form-control {{ $errors->has('status') ? ' is-invalid' : '' }}">
                                            <option value="0">Fechada</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <button type="submit" class="btn btn-outline-info mb-2">
                                        <i class="fa fa-plus"></i>
                                        Cadastrar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/reunioes/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-globe"></i> Administração de Reuniões</h5>
                        <hr>
                        <a href="{{ route('reunioes.index') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-backward"></i> Voltar
                        </a>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="application/x-www-form-urlencoded" novalidate action="{{ route('reunioes.update', $reunio->id) }}">
                            @csrf
                            <div class="form-row align-items-center">
                                <div class="col-sm-12 col-md-12">
                                    <label class="sr-only" for="descricao">Descrição</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-font"></i></div>
                                        </div>
                                        <textarea class="form-control {{ $errors->has('descricao') ? ' is-invalid' : '' }}"
                                                  id="descricao"
                                                  name="descricao"
                                                  placeholder="Descrição da Reunião" required>{{ $reunio->descricao }}</textarea>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-5">
                                    <label class="sr-only" for="data">Data</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                        <input type="date" class="form-control {{ $errors->has('data') ? ' is-invalid' : '' }}"
                                               id="data" name="data">
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-5">
                                    <label class="sr-only" for="status">Status</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-info"></i></div>
                                        </div>
                                        <select id="status" readonly required name="status" class="form-control {{ $errors->has('status') ? ' is-invalid' : '' }}">
                                            <option value="0">Fechada</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <button type="submit" class="btn btn-outline-info mb-2">
                                        <i class="fa fa-plus"></i>
                                        Atualizar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/reunioes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-globe"></i> Administração de Reuniões</h5>
                        <hr>
                        <a href="{{ route('reunioes.create') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-plus"></i> Nova Reunião
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover text-center">
                                <thead>
                                <tr>
                                    <th>N*</th>
                                    <th>Descrição</th>
                                    <th>Data</th>
                                    <th>Relação</th>
                                    <th>Administração</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($reunioes as $re)
                                    <tr>
                                        <td>{{ $re->id }}</td>
                                        <td>{{ $re->descricao }}</td>
                                        <td>{{ date('d-m-Y', strtotime($re->data)) }}</td>
                                        <td>
                                            <a href="#" class="visualizar" data-id="{{ $re->id }}">
                                                <span class="badge badge-info">
                                                    <i class="fa fa-search"></i>
                                                    Visualizar
                                                </span>
                                            </a>
                                        </td>
                                        <td>
                                            <form method="post" enctype="application/x-www-form-urlencoded"
                                                  action="{{ route('reunioes.destroy', $re->id) }}">
                                                @csrf
                                                {{ method_field('DELETE') }}
                                                <a href="{{ route('reunioes.edit', $re->id) }}" data-toggle="tooltip"
                                                   title="Editar" class="btn btn-sm btn-outline-warning">
                                                    <i class="fa fa-pencil-alt"></i>
                                                </a>
                                                <button class="btn btn-sm btn-outline-danger" data-toggle="tooltip"
                                                        title="Excluir">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true"></div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('css/pace/center-radar.css') }}">
@endsection

@push('js')
    <script src="{{ asset('js/pace.js') }}"></script>
    <script>
        $('.visualizar').on('click', function () {
            let id = $(this).data('id');
            let divModal = $('#modal');
            let rota = "/historicoReuniao/" + id;

            $.ajax({
                url: rota,
                beforeSend: function () {
                    $('#app').addClass('')
                },
                error: function (err, xhr) {
                    console.log(xhr)
                },
                success: function (data) {
                    divModal.html(data);
                    divModal.modal('toggle')
                },
                complete: function () {
                    $('#app').removeClass('')
                }
            })
        });
    </script>
@endpush