routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Comuns
Auth::routes();
Route::get('/', 'HomeController@index')->name('inicio');
Route::get('/home', 'HomeController@index')->name('home');

//Block de Registros externos
Route::any('/register', function () {
    return redirect()->route('inicio');
});

//Rotas Administrativas
Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('distribuicao', 'DistribuicaoCrudController');
    Route::resource('reunioes', 'ReuniaoCrudController');
    Route::resource('usuarios', 'UsuarioCrudController');
    Route::resource('entidades', 'OrgaoCrudController');
    Route::resource('pauta', 'PautaCrudController');
    Route::resource('itempauta', 'ItemPautaCrudController');
    Route::get('usuarios-removidos', 'UsuarioCrudController@removidos')->name('removidos');
    Route::post('perma-delete/{id}', 'UsuarioCrudController@forceDelete')->name('delete-user');
    Route::post('restaurar-usuario/{id}', 'UsuarioCrudController@restore')->name('restore-user');
    Route::get('arquivos', 'NovoElfinderController@showIndex')->name('arquivos');
});

//Rota que Altera o Gerenciador de Arquivos
Route::group(array('middleware'=>'auth', 'namespace' => 'Admin'),function(){
    Route::any('connector', ['as' => 'elfinder.connector', 'uses' => 'NovoElfinderController@showConnectorext']);
});

Route::group(['middleware' => 'auth'], function () {
    // Rotas do Perfil
    Route::get('perfil', 'Admin\PerfilController@perfil')->name('perfil');
    Route::put('perfil', 'Admin\PerfilController@perfilUpdate')->name('perfilUpdate');
    Route::put('resetSenha', 'Admin\PerfilController@resetSenha')->name('resetSenha');

    // Rotas da Imagem do Perfil
    Route::put('alterFoto', 'Admin\PerfilController@alterFoto')->name('alterFoto');

    // Rotas das Reuniões - Comuns
    Route::get('reunioes', 'ReuniaoController@index');
    Route::get('reunioes/participar/{reuniao}', 'ReuniaoController@participar')->name('participar');
    Route::post('reunioes/votar', 'ReuniaoController@votar');
    Route::post('reunioes/{reuniao}/abrir', 'ReuniaoController@abrir');
    Route::post('reunioes/{reuniao}/encerrar', 'ReuniaoController@encerrar');
    Route::post('reunioes/{reuniao}/checar', 'ReuniaoController@checar');

    // JSON
    Route::get('reuniao/{reuniao}/load', 'ReuniaoController@loadJSON');
    Route::get('item/{item}/votos', 'ReuniaoController@votosJSON');
    Route::get ('quorum/count/{id}',    'ReuniaoController@quorumCount');
    Route::get ('quorum/users/{id}',    'ReuniaoController@quorumUsers');

    // Rotas de Respostas AJAX
    Route::get('getPautas/{id}', 'AjaxRequestsController@getPautas')->name('getPautas');
    Route::get('getUsers/{id}', 'AjaxRequestsController@getUsers')->name('getQuorum');
    Route::get('getReunions', 'AjaxRequestsController@getReunions')->name('getReunions');
    Route::any('delPauta/{id}', 'AjaxRequestsController@delPauta')->name('delPauta');
    Route::get('addItemView/{id}', 'AjaxRequestsController@addItemView')->name('addItem');
    Route::post('liberarItem/{id}', 'AjaxRequestsController@liberarItem')->name('liberarItem');
    Route::post('encerrarItem/{id}', 'AjaxRequestsController@encerrarItem')->name('encerrarItem');
    Route::get('historicoUser/{user}', 'AjaxRequestsController@historicoUser')->name('historicoUser');
    Route::get('historicoReuniao/{reuniao}', 'AjaxRequestsController@historicoReuniao')->name('historicoReuniao');
});

app/Models/Orgao.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Orgao extends Model
{
    protected $fillable = [
      'nome'
    ];

    public function usuarios()
    {
        return $this->hasMany('App\Models\User', 'orgao_id');
    }

}

resources/views/admin/orgaos/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-university"></i> Administração de Entidades</h5>
                        <hr>
                        <a href="{{ route('entidades.index') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-backward"></i> Voltar
                        </a>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="application/x-www-form-urlencoded" action="{{ route('entidades.store') }}">
                            @csrf
                            <div class="form-row align-items-center">
                                <div class="col-sm-12 col-md-10">
                                    <label class="sr-only" for="orgao">Nome</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-university"></i></div>
                                        </div>
                                        <input type="text" class="form-control" id="orgao" name="nome" placeholder="Nome da Entidade">
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <button type="submit" class="btn btn-outline-info mb-2">
                                        <i class="fa fa-plus"></i>
                                        Cadastrar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/orgaos/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-university"></i>
                            Administração de Entidades</h5>
                        <hr>
                        <a href="{{ route('entidades.index') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-backward"></i> Voltar
                        </a>
                    </div>
                    <div class="card-body">
                        <form method="POST" class="validar" novalidate enctype="application/x-www-form-urlencoded"
                              action="{{ route('entidades.update', $orgao->id) }}">
                            @csrf

                            {{ method_field('PUT') }}

                            <div class="form-row align-items-center">
                                <div class="col-sm-12 col-md-10">
                                    <label class="sr-only" for="orgao">Nome</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-university"></i></div>
                                        </div>
                                        <input type="text"
                                               class="form-control {{ $errors->has('nome') ? ' is-invalid' : '' }}"
                                               id="orgao" name="nome" placeholder="Nome do Entidade"
                                               value="{{ $orgao->nome }}" required>
                                        <div class="invalid-feedback">
                                            Por favor, digite o nome do Entidade
                                        </div>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                        @if ($errors->has('nome'))
                                            <span class="invalid-feedback">
                                                <strong>{{ $errors->first('nome') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <button type="submit" class="btn btn-outline-info mb-2">
                                        <i class="fa fa-share"></i>
                                        Atualizar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('validar');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
@endpush

resources/views/admin/orgaos/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-university"></i> Administração de Entidades</h5>
                        <hr>
                        <a href="{{ route('entidades.create') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-plus"></i> Nova Entidade
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover text-center">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Membros</th>
                                    <th>Administração</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($orgaos as $org)
                                    <tr>
                                        <td>{{ $org->nome }}</td>
                                        <td>
                                            <button type="button" class="visualizar btn btn-outline-info btn-sm"
                                                    data-id="{{ $org->id }}">
                                                Visualizar <span
                                                        class="badge badge-light">{{ $org->usuarios->count() }}</span>
                                            </button>
                                        </td>
                                        <td>
                                            <form method="post" enctype="application/x-www-form-urlencoded" action="{{ route('entidades.destroy', $org->id) }}">
                                                @csrf
                                                {{ method_field('DELETE') }}
                                                <a href="{{ route('entidades.edit', $org->id) }}" data-toggle="tooltip"
                                                   title="Editar" class="btn btn-sm btn-outline-warning">
                                                    <i class="fa fa-pencil-alt"></i>
                                                </a>
                                                <button class="btn btn-sm btn-outline-danger" data-toggle="tooltip" title="Excluir">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true"></div>
@endsection

@push('js')
    <script>
        $('.visualizar').on('click', function () {
            let id = $(this).data("id");
            let rota = "/admin/entidades/" + id;
            let divModal = $('#modal');
            $.ajax({
                url: rota,
                success: function (data) {
                    divModal.html(data);
                    divModal.modal({
                        backdrop: false,
                        show: true
                    }).toggle()
                }
            });
        });
    </script>
@endpush

resources/views/admin/orgaos/show.blade.php
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header dark">
            <h4>Membros</h4>
            <button type="button" class="fechar close" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            @if($membros->count() > 0)
                <table class="table table-bordered">
                    @foreach($membros as $m)
                        <tr>
                            <td>
                        <span class="teste">
                    @if($m->foto)
                                <img src="{{ asset("img/$m->foto") }}" class="ui avatar image">
                            @else
                                <img src="{{ asset('img/default-avatar.png') }}" class="ui avatar image">
                            @endif
                            {{ $m->name }}</span>
                            </td>
                        </tr>
                    @endforeach
                </table>
            @else
                <div class="text-center">
                    <span class="alert alert-warning"><i class="fa fa-exclamation-circle"></i> Não há membros registrados nesta Entidade</span>
                </div>
            @endif
        </div>
        <div class="modal-footer">
            <button type="button" class="fechar btn btn-outline-secondary">Fechar</button>
        </div>
    </div>
</div>

<script>
    $('.fechar').on('click', function () {
        $('#modal').modal().toggle()
    })
</script>