routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Comuns
Auth::routes();
Route::get('/', 'HomeController@index')->name('inicio');
Route::get('/home', 'HomeController@index')->name('home');

//Block de Registros externos
Route::any('/register', function () {
    return redirect()->route('inicio');
});

//Rotas Administrativas
Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('distribuicao', 'DistribuicaoCrudController');
    Route::resource('reunioes', 'ReuniaoCrudController');
    Route::resource('usuarios', 'UsuarioCrudController');
    Route::resource('entidades', 'OrgaoCrudController');
    Route::resource('pauta', 'PautaCrudController');
    Route::resource('itempauta', 'ItemPautaCrudController');
    Route::get('usuarios-removidos', 'UsuarioCrudController@removidos')->name('removidos');
    Route::post('perma-delete/{id}', 'UsuarioCrudController@forceDelete')->name('delete-user');
    Route::post('restaurar-usuario/{id}', 'UsuarioCrudController@restore')->name('restore-user');
    Route::get('arquivos', 'NovoElfinderController@showIndex')->name('arquivos');
});

//Rota que Altera o Gerenciador de Arquivos
Route::group(array('middleware'=>'auth', 'namespace' => 'Admin'),function(){
    Route::any('connector', ['as' => 'elfinder.connector', 'uses' => 'NovoElfinderController@showConnectorext']);
});

Route::group(['middleware' => 'auth'], function () {
    // Rotas do Perfil
    Route::get('perfil', 'Admin\PerfilController@perfil')->name('perfil');
    Route::put('perfil', 'Admin\PerfilController@perfilUpdate')->name('perfilUpdate');
    Route::put('resetSenha', 'Admin\PerfilController@resetSenha')->name('resetSenha');

    // Rotas da Imagem do Perfil
    Route::put('alterFoto', 'Admin\PerfilController@alterFoto')->name('alterFoto');

    // Rotas das Reuniões - Comuns
    Route::get('reunioes', 'ReuniaoController@index');
    Route::get('reunioes/participar/{reuniao}', 'ReuniaoController@participar')->name('participar');
    Route::post('reunioes/votar', 'ReuniaoController@votar');
    Route::post('reunioes/{reuniao}/abrir', 'ReuniaoController@abrir');
    Route::post('reunioes/{reuniao}/encerrar', 'ReuniaoController@encerrar');
    Route::post('reunioes/{reuniao}/checar', 'ReuniaoController@checar');

    // JSON
    Route::get('reuniao/{reuniao}/load', 'ReuniaoController@loadJSON');
    Route::get('item/{item}/votos', 'ReuniaoController@votosJSON');
    Route::get ('quorum/count/{id}',    'ReuniaoController@quorumCount');
    Route::get ('quorum/users/{id}',    'ReuniaoController@quorumUsers');

    // Rotas de Respostas AJAX
    Route::get('getPautas/{id}', 'AjaxRequestsController@getPautas')->name('getPautas');
    Route::get('getUsers/{id}', 'AjaxRequestsController@getUsers')->name('getQuorum');
    Route::get('getReunions', 'AjaxRequestsController@getReunions')->name('getReunions');
    Route::any('delPauta/{id}', 'AjaxRequestsController@delPauta')->name('delPauta');
    Route::get('addItemView/{id}', 'AjaxRequestsController@addItemView')->name('addItem');
    Route::post('liberarItem/{id}', 'AjaxRequestsController@liberarItem')->name('liberarItem');
    Route::post('encerrarItem/{id}', 'AjaxRequestsController@encerrarItem')->name('encerrarItem');
    Route::get('historicoUser/{user}', 'AjaxRequestsController@historicoUser')->name('historicoUser');
    Route::get('historicoReuniao/{reuniao}', 'AjaxRequestsController@historicoReuniao')->name('historicoReuniao');
});

app/Models/Reuniao.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Reuniao extends Model
{
    const STATUS_ABERTO = 1;
    const STATUS_FECHADO = 0;

    protected $table = 'reunioes';

    protected $fillable = [
        'descricao',
        'data',
        'status'
    ];
    protected $casts = [
        'data' => 'date:d-m-Y',
        'status' => 'boolean'
    ];

    protected $dates = [
        'data',
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public function dataExtensa($value)
    {
        return ucfirst(Carbon::createFromTimestampUTC(strtotime($value))->formatLocalized('%A, %d de %B de %Y'));
    }

    public function quorum()
    {
        return $this->belongsToMany('App\Models\ReuniaoUser', 'reunioes_users', 'id', 'reuniao_id');
    }

    public function users()
    {
        return $this->belongsToMany('App\Models\User', 'reunioes_users');
    }

    public function pautas()
    {
        return $this->hasMany('App\Models\Pauta');
    }

    public function ata()
    {
        return false;
    }

    public function aberto()
    {
        return $this->attributes['status'] == STATUS_ABERTO;
    }
}

app/Http/Controllers/ReuniaoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Reuniao;
use App\Models\ItemPauta;
use App\Models\Voto;
use App\Models\ReuniaoUser;
use App\Models\User;

use Illuminate\Http\Request;
use Auth;

class ReuniaoController extends Controller
{
    public function index()
    {
        return view('reuniao.index');
    }

    public function loadJSON(Reuniao $reuniao)
    {
        $reuniao['pautas'] = $reuniao->pautas;
        foreach($reuniao['pautas'] as $pauta) {
            $pauta['items'] = $pauta->items;

            foreach($pauta['items'] as $item) {
                $item->_votoUsuario = $item->votoUsuario(Auth::user()->id);
            }
        }

        return $reuniao->toJson();
    }

    public function votosJSON(ItemPauta $item)
    {
        $votos = $item->votos;
        foreach($votos as $voto) {
            $voto->user_nome = $voto->user->name;
            $voto->item_id = $voto->item_pauta_id;
        }

        return $votos->toJson();
    }

    public function participar(Reuniao $reuniao)
    {
        if (!$reuniao) {
            return redirect('/'); // TODO error handling melhor
        }

        if ($reuniao->status == Reuniao::STATUS_FECHADO && Auth::user()->nivel == 1) {
            return redirect()->route('inicio')->with('error', 'A Reunião está fechada!');
        }



        $registro = ReuniaoUser::where([
            ['user_id', Auth::user()->id],
            ['reuniao_id', $reuniao->id]
        ])->first();

        if (!$registro) {
            ReuniaoUser::create([
                'user_id' => Auth::user()->id,
                'reuniao_id' => $reuniao->id
            ]);

            event(new \App\Events\UserJoinEvent($reuniao->id, Auth::user()));
        }

        return view('reuniao.participar', [
            'reuniao' => $reuniao
        ]);
    }

    public function votar(Request $request)
    {
        $item = ItemPauta::find($request->input('item_pauta_id'));

        if (!$item) {
            // Item não existe
            return response('Item expirado ou erro desconhecido', 500);
        }

        if ($item->status != 'Aberta') {
            // Item não está aberto a votos
            return response('Item fechado ou erro desconhecido', 403);
        }

        if ($item->votoUsuario(Auth::user()->id)) {
            return response('Voto já realizado neste item. Por favor atualize a página e tente novamente', 403);
        }

        $voto = new Voto($request->all());
        $voto->user_id = Auth::user()->id;

        if (!$voto->save()) {
            return response('Falha ao cadastrar voto. Por favor atualize a página e tente novamente', 500);
        }

        event(new \App\Events\VotoStoreEvent($voto));
        return response('Voto realizado com sucesso', 201);
    }

    function quorumCount($reuniao_id)
    {
        return ReuniaoUser::where([
            ['reuniao_id', $reuniao_id]
        ])->count();
    }

    function quorumUsers($reuniao_id)
    {
        $reuniaoUsers = ReuniaoUser::where([
            ['reuniao_id', $reuniao_id]
        ])->get();

        $res = [];

        foreach ($reuniaoUsers as $ru) {
            $user = User::find($ru->user_id);

            if (!$user)
                continue;

            $res[] = [
                "id" => $user->id,
                "name" => $user->name
            ];
        }

        return $res;
    }

    function abrir(Reuniao $reuniao)
    {
        $reuniao->status = 1;
        $reuniao->hora_encerramento = null;
        $reuniao->hora_abertura = date('Y-m-d H:i:s');

        if (!$reuniao->save()) {
            return response('Falha ao cadastrar reunião. Por favor atualize a página e tente novamente', 500);
        }

        event(new \App\Events\ReuniaoStatusEvent($reuniao));
    }

    function encerrar(Reuniao $reuniao)
    {
        $reuniao->status = 0;
        $reuniao->hora_encerramento = date('Y-m-d H:i:s');

        if (!$reuniao->save()) {
            return response('Falha ao cadastrar reunião. Por favor atualize a página e tente novamente', 500);
        }

        event(new \App\Events\ReuniaoStatusEvent($reuniao));
    }

    /**
     * Simula o ReuniaoStatusEvent... corrigir um bug estranho onde o pusher falha com várias abas abertas
     */
    function checar(Reuniao $reuniao)
    {
        $res = (object)[];
        $res->reuniao_id = $reuniao->id;
        $res->status = $reuniao->status;

        $res->aberto = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s' , $reuniao->hora_abertura)->timestamp;

        if ($reuniao->hora_encerramento) {
            $res->encerrado = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s' , $reuniao->hora_encerramento)->timestamp;
            $res->delta = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s' , $reuniao->hora_encerramento)
                ->diffInSeconds(\Carbon\Carbon::createFromFormat('Y-m-d H:i:s' , $reuniao->hora_abertura));
        } else {
            $res->encerrado = 0;
        }

        return json_encode($res);
    }
}

resources/views/reuniao/ajax/itemPautaModal.blade.php
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header bg-info">
            <h5 class="modal-title text-white">Incluir Item na Pauta: {{ $pauta->nome }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="addItemForm" action="{{ route('itempauta.store') }}" class="needs-validation" novalidate
              method="POST" enctype="application/x-www-form-urlencoded">
            {!! csrf_field() !!}
            <div class="modal-body">
                <div class="form-row">
                    <div class="col-md-12 mb-3">
                        <input type="text" class="form-control" id="nome" name="nome" placeholder="Descrição"
                               required>
                        <div class="valid-feedback">
                            Ok !
                        </div>
                    </div>
                    <div class="col-md-12 mb-3">
                        <textarea class="form-control ckeditor" id="ckeditor-content" name="texto" placeholder="Texto"></textarea>
                        <div class="valid-feedback">
                            Ok !
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" name="pauta_id" value="{{ $pauta->id }}">
                <button type="submit" class="btn btn-primary">Adicionar</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </div>
        </form>
    </div>
</div>

<script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
<script>
    jQuery(document).ready(function($) {
        $('.ckeditor').ckeditor({
            "filebrowserBrowseUrl": "{{ url('/admin/elfinder/ckeditor') }}",
            "extraPlugins" : 'oembed,widget'
        });
    });
</script>
<script src="{{ url('/vendor/colorbox/jquery.colorbox-min.js') }}"></script>
<script>
    $(document).on('click','.popup_selector[data-inputid=image-filemanager]',function (event) {
        event.preventDefault();
        var triggerUrl = "{{ url('/admin/elfinder/popup/image-filemanager') }}";
        $.colorbox({
            href: triggerUrl,
            fastIframe: true,
            iframe: true,
            width: '80%',
            height: '80%'
        });
    });

    function processSelectedFile(filePath, requestingField) {
        $('#' + requestingField).val(filePath.replace(/\\/g,"/"));
    }

    $(document).on('click','.clear_elfinder_picker[data-inputid=image-filemanager]',function (event) {
        event.preventDefault();
        var updateID = $(this).attr('data-inputid'); // Btn id clicked
        $("#"+updateID).val("");
    });
</script>

resources/views/reuniao/ajax/lista.blade.php
@foreach($reunioes as $reuniao)
    <div class="row">
        @php($status = $reuniao->status == \App\Models\Reuniao::STATUS_ABERTO)

        <div class="col-12 mb-2">
            <div class="card text-center {{ $status ? 'border-primary' : 'border-success' }}">
                <div class="card-header {{ $status ? 'text-primary' : 'text-muted' }}">
                    @if($status)
                        <p style="margin: 0;">Aberta</p>
                    @else
                        <p style="margin: 0;">Fechada</p>
                    @endif
                </div>
                <div class="card-body {{ $status ? 'text-primary' : 'text-success' }}">
                    <h4>
                        {{ $reuniao->descricao }}</h4>
                    <div class="text-muted">
                        <i class="fa fa-calendar"></i>
                        {{ $reuniao->dataExtensa($reuniao->created_at) }}
                    </div>
                </div>
                <div class="card-footer">
                    @if($status)
                        <a class="btn btn-primary" href="/reunioes/participar/{!! $reuniao->id !!}">
                            Entrar
                            <i class="fa fa-arrow-right"></i>
                        </a>
                    @else
                        @if($reuniao->ata())
                            <p class="text-muted" style="margin: 0;">Reunião Encerrada</p>
                            <button class="btn btn-outline-secondary">
                                <i class="fa fa-search"></i>
                                Visualizar Ata
                            </button>
                        @elseif (Auth::user()->nivel == 0)
                            <a href="/reunioes/participar/{!! $reuniao->id !!}" class="btn btn-outline-info">
                                <i class="fa fa-globe"></i>
                                Gerenciar Reunião
                            </a>
                        @else
                            <p class="text-muted" style="margin: 0;">Aguardando...</p>
                        @endif
                    @endif
                </div>
            </div>
        </div>
    </div>
@endforeach

resources/views/reuniao/ajax/pautas.blade.php
<li class="nav-item text-center list-group-item active">
    <h1>Pautas</h1>
</li>
@foreach($reuniao->pautas as $pauta)
    <li class="nav-item list-group-item ">
        @if(count($pauta->items))
            <a class="btn btn-link nav-link" data-toggle="collapse"
               data-target="#pauta{!! $pauta->id !!}" style="text-align: left">
                <span class="reuniao-item"><i class="fa fa-fw fa-chevron-circle-down"></i></span>
                {{ $pauta->nome }}
            </a>
        @else
            <span class="btn" style="text-align: left">
                <span class="reuniao-item"><i class="fa fa-dot-circle"></i></span>
                {{ $pauta->nome }}
            </span>
        @endif
        @if(Auth::user()->nivel == 0)
            <a data-id="{{$pauta->id}}" class="btn text-white btn-sm btn-primary addItem"><i
                        class="fa fa-plus fa-sm"></i> Add Item</a>
            <a data-id="{{$pauta->id}}" class="btn text-white btn-sm btn-danger delPauta"><i
                        class="fa fa-ban fa-sm"></i> Remover</a>
        @endif
    </li>

    @if($pauta->items)
        <div class="collapse" id="pauta{!! $pauta->id !!}"
             data-parent="#accordAndamento">
            <ul class="nav list-group flex-column">
                @foreach($pauta->items as $item)
                    @php($status = $item->status == 'Aberta' ? 'btn-aberto' : 'btn-fechado')
                    <li class="nav-item list-group-item"
                        @if($item->status != 'Aberta') style='background-color: #5552;' @endif>
                        <div class="btn btn-link nav-link text-left {{ $item->status == 'Aberta' ? 'aberto' : 'fechado' }}"
                             data-toggle="collapse"
                             data-target="#texto{!! $item->id !!}">
                            @if(Auth::user()->nivel == 0)
                                @if($item->status == 'Aberta')
                                    <button class="btn btn-sm btn-danger {{ $status }}" data-id="{{ $item->id }}">
                                        <i class="fa fa-fw fa-lock" title="Encerrar"></i>
                                    </button>
                                @elseif($item->status == 'Fechada')
                                    <button class="btn btn-sm btn-success {{ $status }}" data-id="{{ $item->id }}">
                                        <i class="fa fa-fw fa-lock-open" title="Liberar Item"></i>
                                    </button>
                                @elseif($item->status == 'Encerrada')
                                    <button class="btn btn-sm btn-warning {{ $status }}" data-id="{{ $item->id }}">
                                        <i class="fa fa-fw fa-exclamation-circle" title="Encerrada"></i>
                                    </button>
                                @endif
                            @endif
                            {{ $item->nome }}
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
    @endif
@endforeach

<script>

    setTimeout(function (e) {
        let delPauta = $('.delPauta');
        delPauta.on('click', function () {
            let dpId = $(this).data('id');
            $.ajax({
                url: '/delPauta/' + dpId,
                success: function (data) {
                    console.log(data)
                },
                error: function (err, xhr) {
                    console.log(err)
                }
            })
        });


        let addItem = $('.addItem');
        let addItemDiv = $('#addItemDiv');

        addItem.on('click', function () {
            let addId = $(this).data('id');
            $.ajax({
                url: '/addItemView/' + addId,
                error: function (err, xhr) {
                    console.log(xhr)
                },
                success: function (data) {
                    addItemDiv.html(data);
                    addItemDiv.modal('toggle');
                },
            })
        });
    }, 2000);
</script>

@if(Auth::user()->nivel == 0)
    <script>
        setTimeout(function (e) {
            let openItem = $('.btn-fechado');
            openItem.on('click', function () {
                let oiId = $(this).data('id');
                $.ajax({
                    url: '/liberarItem/' + oiId,
                    error: function (err, xhr) {
                        $(this).removeClass('fechado');
                        $(this).addClass('aberto')
                    },
                    success: function (data) {
                        loadPauta();
                        $(this).removeClass('fechado');
                        $(this).addClass('aberto')
                    }
                })
            });

            let fecharItem = $('.btn-aberto');
            fecharItem.on('click', function () {
                let oiId = $(this).data('id');
                $.ajax({
                    url: '/encerrarItem/' + oiId,
                    error: function (err, xhr) {

                    },
                    success: function (data) {
                        loadPauta();
                        $(this).removeClass('aberto');
                        $(this).addClass('encerrado')
                    }
                })
            });
        }, 2000)
    </script>
@endif

resources/views/reuniao/ajax/quorum.blade.php
@foreach($reuniao->users as $presentes)
    <li class="list-inline-item">
        <button type="button" class="btn btn-outline-secondary" disabled>
            @if($presentes->foto)
                <img src="{{ asset("arquivos/$presentes->foto") }}" style="max-width: 25px"
                     class="rounded-circle">
            @else
                <img src="http://10.155.17.70:3000/img/default-avatar.png" style="max-width: 25px"
                     class="rounded-circle">
            @endif
            {{ $presentes->name }}
        </button>
    </li>
@endforeach