routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Comuns
Auth::routes();
Route::get('/', 'HomeController@index')->name('inicio');
Route::get('/home', 'HomeController@index')->name('home');

//Block de Registros externos
Route::any('/register', function () {
    return redirect()->route('inicio');
});

//Rotas Administrativas
Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('distribuicao', 'DistribuicaoCrudController');
    Route::resource('reunioes', 'ReuniaoCrudController');
    Route::resource('usuarios', 'UsuarioCrudController');
    Route::resource('entidades', 'OrgaoCrudController');
    Route::resource('pauta', 'PautaCrudController');
    Route::resource('itempauta', 'ItemPautaCrudController');
    Route::get('usuarios-removidos', 'UsuarioCrudController@removidos')->name('removidos');
    Route::post('perma-delete/{id}', 'UsuarioCrudController@forceDelete')->name('delete-user');
    Route::post('restaurar-usuario/{id}', 'UsuarioCrudController@restore')->name('restore-user');
    Route::get('arquivos', 'NovoElfinderController@showIndex')->name('arquivos');
});

//Rota que Altera o Gerenciador de Arquivos
Route::group(array('middleware'=>'auth', 'namespace' => 'Admin'),function(){
    Route::any('connector', ['as' => 'elfinder.connector', 'uses' => 'NovoElfinderController@showConnectorext']);
});

Route::group(['middleware' => 'auth'], function () {
    // Rotas do Perfil
    Route::get('perfil', 'Admin\PerfilController@perfil')->name('perfil');
    Route::put('perfil', 'Admin\PerfilController@perfilUpdate')->name('perfilUpdate');
    Route::put('resetSenha', 'Admin\PerfilController@resetSenha')->name('resetSenha');

    // Rotas da Imagem do Perfil
    Route::put('alterFoto', 'Admin\PerfilController@alterFoto')->name('alterFoto');

    // Rotas das Reuniões - Comuns
    Route::get('reunioes', 'ReuniaoController@index');
    Route::get('reunioes/participar/{reuniao}', 'ReuniaoController@participar')->name('participar');
    Route::post('reunioes/votar', 'ReuniaoController@votar');
    Route::post('reunioes/{reuniao}/abrir', 'ReuniaoController@abrir');
    Route::post('reunioes/{reuniao}/encerrar', 'ReuniaoController@encerrar');
    Route::post('reunioes/{reuniao}/checar', 'ReuniaoController@checar');

    // JSON
    Route::get('reuniao/{reuniao}/load', 'ReuniaoController@loadJSON');
    Route::get('item/{item}/votos', 'ReuniaoController@votosJSON');
    Route::get ('quorum/count/{id}',    'ReuniaoController@quorumCount');
    Route::get ('quorum/users/{id}',    'ReuniaoController@quorumUsers');

    // Rotas de Respostas AJAX
    Route::get('getPautas/{id}', 'AjaxRequestsController@getPautas')->name('getPautas');
    Route::get('getUsers/{id}', 'AjaxRequestsController@getUsers')->name('getQuorum');
    Route::get('getReunions', 'AjaxRequestsController@getReunions')->name('getReunions');
    Route::any('delPauta/{id}', 'AjaxRequestsController@delPauta')->name('delPauta');
    Route::get('addItemView/{id}', 'AjaxRequestsController@addItemView')->name('addItem');
    Route::post('liberarItem/{id}', 'AjaxRequestsController@liberarItem')->name('liberarItem');
    Route::post('encerrarItem/{id}', 'AjaxRequestsController@encerrarItem')->name('encerrarItem');
    Route::get('historicoUser/{user}', 'AjaxRequestsController@historicoUser')->name('historicoUser');
    Route::get('historicoReuniao/{reuniao}', 'AjaxRequestsController@historicoReuniao')->name('historicoReuniao');
});

resources/views/admin/usuarios/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-street-view"></i> Administração de Usuários</h5>
                        <hr>
                        <a href="{{ route('usuarios.index') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-backward"></i> Voltar
                        </a>
                    </div>
                    <div class="card-body">
                        <form method="POST" class="validar" novalidate enctype="application/x-www-form-urlencoded"
                              action="{{ route('usuarios.store') }}">
                            @csrf
                            <div class="form-row align-items-center">
                                <div class="col-sm-12">
                                    <label class="sr-only" for="name">Nome</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-user"></i></div>
                                        </div>
                                        <input type="text"
                                               class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}"
                                               id="name" name="name" placeholder="Nome do Usuário"
                                               value="{{ old('name') }}"
                                               required>
                                        <div class="invalid-feedback">
                                            Por favor, verifique este campo
                                        </div>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <label class="sr-only" for="name">Usuário</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-street-view"></i></div>
                                        </div>
                                        <input type="text"
                                               class="form-control {{ $errors->has('usuario') ? ' is-invalid' : '' }}"
                                               id="usuario" name="usuario" placeholder="Usuário"
                                               value="{{ old('usuario') }}"
                                               required>
                                        <div class="invalid-feedback">
                                            Por favor, verifique este campo
                                        </div>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <label class="sr-only" for="email">E-mail</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-envelope"></i></div>
                                        </div>
                                        <input type="email"
                                               class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}"
                                               id="email" name="email" placeholder="E-mail" value="{{ old('email') }}"
                                               required>
                                        <div class="invalid-feedback">
                                            Por favor, verifique este campo
                                        </div>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <label class="sr-only" for="password">Senha</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-key"></i></div>
                                        </div>
                                        <input type="password"
                                               class="form-control {{ $errors->has('password') ? ' is-invalid' : '' }}"
                                               id="password" name="password" placeholder="Senha"
                                               value="{{ old('password') }}"
                                               required>
                                        <div class="invalid-feedback">
                                            Por favor, verifique este campo
                                        </div>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <label class="sr-only" for="password_confirmation">Confirme a Senha</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-key"></i></div>
                                        </div>
                                        <input type="password"
                                               class="form-control {{ $errors->has('password_confirmation') ? ' is-invalid' : '' }}"
                                               id="password_confirmation" name="password_confirmation"
                                               placeholder="Confirme a Senha" value="{{ old('password_confirmation') }}"
                                               required>
                                        <div class="invalid-feedback">
                                            Por favor, verifique este campo
                                        </div>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <label class="sr-only" for="telefone">Telefone</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-phone"></i></div>
                                        </div>
                                        <input type="tel"
                                               class="form-control {{ $errors->has('telefone') ? ' is-invalid' : '' }}"
                                               id="telefone" name="telefone" placeholder="Telefone"
                                               value="{{ old('telefone') }}"
                                        >
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-4">
                                    <label class="sr-only" for="orgao">Orgão</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-university"></i></div>
                                        </div>
                                        <select class="form-control {{ $errors->has('orgao_id') ? ' is-invalid' : '' }}"
                                                id="orgao" name="orgao_id" required>
                                            @foreach($orgaos as $org)
                                                <option value="{{ $org->id }}" {{ (old("orgao_id") == $org->id ? "selected":"") }}>{{ $org->nome }}</option>
                                            @endforeach
                                        </select>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-4">
                                    <label class="sr-only" for="ativo">Ativo</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-globe"></i></div>
                                        </div>
                                        <select class="form-control {{ $errors->has('ativo') ? ' is-invalid' : '' }}"
                                                id="ativo" name="ativo" required>
                                            <option value="1" @if(old('ativo') == 1) selected @endif>Ativo</option>
                                            <option value="0" @if(old('ativo') == 0) selected @endif>Inativo</option>
                                        </select>
                                        <div class="invalid-feedback">
                                            Por favor, verifique este campo
                                        </div>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-4">
                                    <label class="sr-only" for="nivel">Nível</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-gavel"></i></div>
                                        </div>
                                        <select class="form-control {{ $errors->has('nivel') ? ' is-invalid' : '' }}"
                                                id="nivel" name="nivel" required>
                                            <option value="1" @if(old('nivel') == 1) selected @endif>Comum</option>
                                            <option value="0" @if(old('nivel') == 0) selected @endif>Administrador
                                            </option>
                                        </select>
                                        <div class="invalid-feedback">
                                            Por favor, verifique este campo
                                        </div>
                                        <div class="valid-feedback">
                                            <i class="fa fa-check-circle"></i> Ok
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-outline-info btn-block mb-2">
                                        <i class="fa fa-plus"></i>
                                        Criar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
<script>
    var pass = $('#password');
    var passcon = $('#password_confirmation');

    function length(e) {
        return e.val().length >= 6
    }

    function equal() {
        return pass.html === passcon.html
    }

    pass.on('keyup', function() {
        if (length(pass) === true){
            pass.removeClass('is-invalid');
            pass.addClass('is-valid')
        } else {
            pass.removeClass('is-valid');
            pass.addClass('is-invalid')
        }
    });

    passcon.on('keyup', function() {
        if (length(passcon) && equal() === true){
            passcon.removeClass('is-invalid');
            passcon.addClass('is-valid')
        } else {
            passcon.removeClass('is-valid');
            passcon.addClass('is-invalid');
        }
    });
</script>
@endpush

resources/views/admin/usuarios/index.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/pace/center-radar.css') }}">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-street-view"></i>
                             Administração de Usuários</h5>
                        <hr>
                        <a href="{{ route('usuarios.create') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-plus"></i> Novo Usuário
                        </a>
                        <a href="{{ route('removidos') }}" class="btn btn-outline-danger btn-sm">
                            <i class="fa fa-ban"></i> Usuários Removidos
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover text-center">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>E-mail</th>
                                    <th>Telefone</th>
                                    <th>Orgão</th>
                                    <th>Ativo</th>
                                    <th>Nível</th>
                                    <th>Histórico</th>
                                    <th>Administração</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($usuarios as $usr)
                                    <tr>
                                        <td>{{ $usr->name }}</td>
                                        <td>{{ $usr->email }}</td>
                                        <td>{{ $usr->telefone }}</td>
                                        <td>{{ $usr->orgao->nome }}</td>
                                        <td>
                                            @if ($usr->ativo == 1)
                                                <i class="fa fa-check" style="color: green"></i>
                                            @else
                                                <i class="fa fa-ban" style="color: red"></i>
                                            @endif
                                        </td>
                                        <td>
                                            @if ($usr->nivel == 0)
                                                <span class="badge badge-dark">
                                                <i class="fa fa-user-secret"></i> Administrador
                                                </span>
                                            @else
                                                <span class="badge badge-secondary">
                                                <i class="fa fa-user"></i> Comum
                                                </span>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="#" class="visualizar" data-id="{{ $usr->id }}">
                                                <span class="badge badge-info">
                                                    <i class="fa fa-search"></i>
                                                    Visualizar
                                                </span>
                                            </a>
                                        </td>
                                        <td>
                                            <form method="post" enctype="application/x-www-form-urlencoded"
                                                  action="{{ route('usuarios.destroy', $usr->id) }}">
                                                @csrf
                                                {{ method_field('DELETE') }}
                                                <a href="{{ route('usuarios.edit', $usr->id) }}" data-toggle="tooltip"
                                                   title="Editar" class="btn btn-sm btn-outline-warning">
                                                    <i class="fa fa-pencil-alt"></i>
                                                </a>
                                                <button class="btn btn-sm btn-outline-danger" data-toggle="tooltip"
                                                        title="Excluir">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true"></div>
@endsection

@push('js')
    <script src="{{ asset('js/pace.js') }}"></script>
    <script>
        $('.visualizar').on('click', function () {
            let id = $(this).data('id');
            let divModal = $('#modal');
            let rota = "/historicoUser/" + id;

            $.ajax({
                url: rota,
                error: function (err, xhr) {
                    console.log(xhr)
                },
                success: function (data) {
                    divModal.html(data);
                    divModal.modal('toggle')
                }
            })
        });
    </script>
@endpush

resources/views/admin/usuarios/removidos.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h5><i class="fa fa-street-view"></i>
                             Administração de Usuários</h5>
                        <hr>
                        <a href="{{ route('usuarios.index') }}" class="btn btn-outline-primary btn-sm">
                            <i class="fa fa-backward"></i> Voltar
                        </a>
                        <a href="{{ route('usuarios.create') }}" class="btn btn-outline-info btn-sm">
                            <i class="fa fa-plus"></i> Novo Usuário
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover text-center">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>E-mail</th>
                                    <th>Telefone</th>
                                    <th>Orgão</th>
                                    <th>Ativo</th>
                                    <th>Nível</th>
                                    <th>Histórico</th>
                                    <th>Administração</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($usuarios as $usr)
                                    <tr>
                                        <td>{{ $usr->name }}</td>
                                        <td>{{ $usr->email }}</td>
                                        <td>{{ $usr->telefone }}</td>
                                        <td>{{ $usr->orgao->nome }}</td>
                                        <td>
                                            @if ($usr->ativo == 1)
                                                <i class="fa fa-check" style="color: green"></i>
                                            @else
                                                <i class="fa fa-ban" style="color: red"></i>
                                            @endif
                                        </td>
                                        <td>
                                            @if ($usr->nivel == 0)
                                                <span class="badge badge-dark">
                                                <i class="fa fa-user-secret"></i> Administrador
                                                </span>
                                            @else
                                                <span class="badge badge-secondary">
                                                <i class="fa fa-user"></i> Comum
                                                </span>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="#" class="visualizar" data-id="{{ $usr->id }}">
                                                <span class="badge badge-info">
                                                    <i class="fa fa-search"></i>
                                                    Visualizar
                                                </span>
                                            </a>
                                        </td>
                                        <td>
                                            <form method="post" style="display: inline" enctype="application/x-www-form-urlencoded"
                                                  action="{{ route('restore-user', $usr->id) }}">
                                                @csrf
                                                <button class="btn btn-sm btn-outline-primary" data-toggle="tooltip"
                                                        title="Restaurar">
                                                    <i class="fa fa-history"></i>
                                                </button>
                                            </form>
                                            <form method="post" style="display: inline" enctype="application/x-www-form-urlencoded"
                                                  action="{{ route('delete-user', $usr->id) }}">
                                                @csrf
                                                <button class="btn btn-sm btn-outline-danger" data-toggle="tooltip"
                                                        title="Excluir">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true"></div>
@endsection

@push('js')
    <script>
        $('.visualizar').on('click', function () {
            let id = $(this).data("id");
            let rota = "/admin/usuarios/" + id;
            let divModal = $('#modal');
            $.ajax({
                url: rota,
                success: function (data) {
                    divModal.html(data);
                    divModal.modal({
                        backdrop: false,
                        show: true
                    }).toggle()
                }
            });
        });
    </script>
@endpush